/**
 * Language layer — English 🇬🇧 / বাংলা 🇧🇩 / Banglish (Bangla written in Latin).
 * ---------------------------------------------------------------------------
 * MY-AI must understand a user who writes:
 *
 *    "what is the capital of Bangladesh?"      → English
 *    "বাংলাদেশের রাজধানী কী?"                  → Bangla
 *    "Bangladesher rajdhani ki?"               → Banglish
 *    "amar nam ki? tell me please"             → mixed Banglish + English
 *
 * Everything here is offline, dependency-free and deterministic:
 *
 *   • `detectLanguage()`      — which of the three the message is written in
 *   • `banglishToBengali()`   — word-level transliteration using a curated
 *                               dictionary of 1000+ common Banglish
 *                               words (plus a phonetic fallback for the rest)
 *   • `normalizeForMatch()`   — one canonical Latin form of ANY of the three
 *                               scripts, so a single regex can match all of
 *                               them (this is what powers intents + memory)
 *   • `t()`                   — pick the reply variant for the user's language
 *
 * The point: the rest of the brain (intents, memory, retrieval, research)
 * only ever deals with normalised text, so it works identically in all three.
 */

export type Lang = "en" | "bn" | "banglish";

const BENGALI_RE = /[\u0980-\u09FF]/;
const LATIN_RE = /[A-Za-z]/;

/** How much of the message is written in the Bengali script (0…1). */
export function bengaliRatio(text: string): number {
  const letters = text.match(/[\p{L}]/gu) ?? [];
  if (letters.length === 0) return 0;
  const bengali = letters.filter((c) => BENGALI_RE.test(c)).length;
  return bengali / letters.length;
}

// ---------------------------------------------------------------------------
// Banglish → Bengali dictionary
// ---------------------------------------------------------------------------

/**
 * Curated Banglish → Bengali word map.
 * Keys are lowercase, punctuation-free Latin words. Multiple spellings of the
 * same word (ki / kii / kee) all map to the same Bengali word, because people
 * genuinely type them all.
 */
export const BANGLISH_WORDS: Record<string, string> = {
  "ki": "কি",
  "kii": "কি",
  "kee": "কি",
  "kie": "কি",
  "key": "কি",
  "kee2": "কী",
  "ke": "কে",
  "kea": "কে",
  "kay": "কে",
  "kake": "কাকে",
  "kakei": "কাকে",
  "kar": "কার",
  "kaar": "কার",
  "kara": "কারা",
  "kaara": "কারা",
  "kader": "কাদের",
  "kaader": "কাদের",
  "keno": "কেন",
  "kano": "কেন",
  "kn": "কেন",
  "kenno": "কেন",
  "kivabe": "কীভাবে",
  "kibhabe": "কীভাবে",
  "kemne": "কীভাবে",
  "kmne": "কীভাবে",
  "kivabeh": "কীভাবে",
  "kemon": "কেমন",
  "kmn": "কেমন",
  "kemonn": "কেমন",
  "kemun": "কেমন",
  "kothay": "কোথায়",
  "kothae": "কোথায়",
  "kothai": "কোথায়",
  "kuthay": "কোথায়",
  "kobe": "কবে",
  "kobey": "কবে",
  "kokhon": "কখন",
  "kkhn": "কখন",
  "kokhn": "কখন",
  "koto": "কত",
  "kto": "কত",
  "kotoi": "কত",
  "kotota": "কতটা",
  "kototaa": "কতটা",
  "kotokhon": "কতক্ষণ",
  "kotokkhon": "কতক্ষণ",
  "kotodin": "কতদিন",
  "kon": "কোন",
  "konn": "কোন",
  "kono": "কোনো",
  "konta": "কোনটা",
  "kontaa": "কোনটা",
  "kongulo": "কোনগুলো",
  "kongula": "কোনগুলো",
  "keu": "কেউ",
  "keo": "কেউ",
  "kichu": "কিছু",
  "kisu": "কিছু",
  "kicu": "কিছু",
  "kichui": "কিছুই",
  "kisui": "কিছুই",
  "koyta": "কয়টা",
  "koita": "কয়টা",
  "koytaa": "কয়টা",
  "kotojon": "কতজন",
  "ami": "আমি",
  "aami": "আমি",
  "amar": "আমার",
  "aamar": "আমার",
  "amake": "আমাকে",
  "amakei": "আমাকে",
  "amra": "আমরা",
  "amraa": "আমরা",
  "amader": "আমাদের",
  "tumi": "তুমি",
  "tomar": "তোমার",
  "tomake": "তোমাকে",
  "tomra": "তোমরা",
  "tomader": "তোমাদের",
  "apni": "আপনি",
  "apnee": "আপনি",
  "apnar": "আপনার",
  "apnaar": "আপনার",
  "apnake": "আপনাকে",
  "apnara": "আপনারা",
  "tui": "তুই",
  "tor": "তোর",
  "toke": "তোকে",
  "se": "সে",
  "she": "সে",
  "tar": "তার",
  "taar": "তার",
  "take": "তাকে",
  "takee": "তাকে",
  "tara": "তারা",
  "taraa": "তারা",
  "tader": "তাদের",
  "taader": "তাদের",
  "eta": "এটা",
  "eita": "এটা",
  "ita": "এটা",
  "ota": "ওটা",
  "otaa": "ওটা",
  "woita": "ওটা",
  "eti": "এটি",
  "oti": "ওটি",
  "egulo": "এগুলো",
  "egula": "এগুলো",
  "eigulo": "এগুলো",
  "ogulo": "ওগুলো",
  "ogula": "ওগুলো",
  "ei": "এই",
  "eyi": "এই",
  "oi": "ওই",
  "woi": "ওই",
  "sei": "সেই",
  "shei": "সেই",
  "ekhane": "এখানে",
  "ikhane": "এখানে",
  "okhane": "ওখানে",
  "sekhane": "সেখানে",
  "shekhane": "সেখানে",
  "ekhon": "এখন",
  "akhon": "এখন",
  "ekhn": "এখন",
  "tokhon": "তখন",
  "tokhn": "তখন",
  "pore": "পরে",
  "porey": "পরে",
  "age": "আগে",
  "aage": "আগে",
  "agey": "আগে",
  "nije": "নিজে",
  "nijer": "নিজের",
  "nijeke": "নিজেকে",
  "ache": "আছে",
  "ase": "আছে",
  "asey": "আছে",
  "achey": "আছে",
  "achi": "আছি",
  "acho": "আছো",
  "aso": "আছো",
  "achho": "আছো",
  "achen": "আছেন",
  "asen": "আছেন",
  "chilo": "ছিল",
  "silo": "ছিল",
  "chilam": "ছিলাম",
  "silam": "ছিলাম",
  "chile": "ছিলে",
  "sile": "ছিলে",
  "chilen": "ছিলেন",
  "silen": "ছিলেন",
  "nai": "নেই",
  "nei": "নেই",
  "hoy": "হয়",
  "hoi": "হয়",
  "hoye": "হয়ে",
  "hoiye": "হয়ে",
  "hobe": "হবে",
  "holo": "হলো",
  "hoilo": "হলো",
  "hoyeche": "হয়েছে",
  "hoise": "হয়েছে",
  "hoiyeche": "হয়েছে",
  "hocche": "হচ্ছে",
  "howa": "হওয়া",
  "hoa": "হওয়া",
  "hole": "হলে",
  "holei": "হলেই",
  "hote": "হতে",
  "hobo": "হব",
  "hob": "হব",
  "hoben": "হবেন",
  "korbo": "করব",
  "koro": "করো",
  "korte": "করতে",
  "kore": "করে",
  "korchi": "করছি",
  "korlam": "করলাম",
  "korben": "করবেন",
  "korba": "করবা",
  "kora": "করা",
  "koreche": "করেছে",
  "korse": "করেছে",
  "korche": "করছে",
  "korun": "করুন",
  "kori": "করি",
  "koren": "করেন",
  "korle": "করলে",
  "korlei": "করলেই",
  "koray": "করায়",
  "korano": "করানো",
  "bolo": "বলো",
  "bol": "বল",
  "bolte": "বলতে",
  "bole": "বলে",
  "bolbo": "বলব",
  "bolen": "বলেন",
  "bolchi": "বলছি",
  "bollam": "বললাম",
  "bola": "বলা",
  "boleche": "বলেছে",
  "bolse": "বলেছে",
  "bolun": "বলুন",
  "boli": "বলি",
  "bolle": "বললে",
  "jani": "জানি",
  "jano": "জানো",
  "janen": "জানেন",
  "jante": "জানতে",
  "janao": "জানাও",
  "jana": "জানা",
  "janbo": "জানব",
  "janchi": "জানছি",
  "janlam": "জানলাম",
  "janenni": "জানেননি",
  "dekho": "দেখো",
  "dekhi": "দেখি",
  "dekhte": "দেখতে",
  "dekha": "দেখা",
  "dekhbo": "দেখব",
  "dekhchi": "দেখছি",
  "dekhlam": "দেখলাম",
  "dekhun": "দেখুন",
  "dekhen": "দেখেন",
  "dekhe": "দেখে",
  "chai": "চাই",
  "chao": "চাও",
  "chan": "চান",
  "chaibo": "চাইব",
  "chabo": "চাইব",
  "chaoa": "চাওয়া",
  "lagbe": "লাগবে",
  "lage": "লাগে",
  "laglo": "লাগল",
  "lagche": "লাগছে",
  "dao": "দাও",
  "den": "দেন",
  "dite": "দিতে",
  "diye": "দিয়ে",
  "dibo": "দিব",
  "dilam": "দিলাম",
  "diyeche": "দিয়েছে",
  "dise": "দিয়েছে",
  "dichchi": "দিচ্ছি",
  "din": "দিন",
  "dewa": "দেওয়া",
  "deoa": "দেওয়া",
  "nao": "নাও",
  "nite": "নিতে",
  "niye": "নিয়ে",
  "nibo": "নিব",
  "nilam": "নিলাম",
  "newa": "নেওয়া",
  "nin": "নিন",
  "jao": "যাও",
  "jabo": "যাব",
  "jai": "যাই",
  "jete": "যেতে",
  "jacchi": "যাচ্ছি",
  "gelam": "গেলাম",
  "geche": "গেছে",
  "gese": "গেছে",
  "jaoa": "যাওয়া",
  "jawa": "যাওয়া",
  "jan": "যান",
  "gele": "গেলে",
  "gelo": "গেল",
  "asbe": "আসবে",
  "ashbe": "আসবে",
  "asho": "আসো",
  "esechi": "এসেছি",
  "asha": "আসা",
  "asa": "আসা",
  "aschhi": "আসছি",
  "aschi": "আসছি",
  "eseche": "এসেছে",
  "ese": "এসেছে",
  "ashun": "আসুন",
  "ashi": "আসি",
  "asi": "আসি",
  "elam": "এলাম",
  "ele": "এলে",
  "parbo": "পারব",
  "paro": "পারো",
  "paren": "পারেন",
  "pari": "পারি",
  "parbe": "পারবে",
  "para": "পারা",
  "parini": "পারিনি",
  "parlam": "পারলাম",
  "thako": "থাকো",
  "thaki": "থাকি",
  "thakbe": "থাকবে",
  "thaka": "থাকা",
  "thaken": "থাকেন",
  "thakchi": "থাকছি",
  "thaklam": "থাকলাম",
  "thakle": "থাকলে",
  "khai": "খাই",
  "khao": "খাও",
  "kheye": "খেয়ে",
  "khabo": "খাব",
  "khawa": "খাওয়া",
  "khaoa": "খাওয়া",
  "khacchi": "খাচ্ছি",
  "khelam": "খেলাম",
  "khan": "খান",
  "kheyeche": "খেয়েছে",
  "suru": "শুরু",
  "shuru": "শুরু",
  "sesh": "শেষ",
  "shesh": "শেষ",
  "likhe": "লিখে",
  "likho": "লিখো",
  "lekha": "লেখা",
  "likhbo": "লিখব",
  "likhchi": "লিখছি",
  "sikhi": "শিখি",
  "shikhi": "শিখি",
  "sikhbo": "শিখব",
  "shikhbo": "শিখব",
  "shikha": "শেখা",
  "sikha": "শেখা",
  "shikhao": "শেখাও",
  "sikhao": "শেখাও",
  "pori": "পড়ি",
  "poro": "পড়ো",
  "porte": "পড়তে",
  "pora": "পড়া",
  "porbo": "পড়ব",
  "porchi": "পড়ছি",
  "pore2": "পড়ে",
  "bujhi": "বুঝি",
  "bujho": "বুঝো",
  "bujhen": "বুঝেন",
  "bujhte": "বুঝতে",
  "bujhlam": "বুঝলাম",
  "bhabi": "ভাবি",
  "vabi": "ভাবি",
  "bhabo": "ভাবো",
  "vabo": "ভাবো",
  "bhabchi": "ভাবছি",
  "bhebe": "ভেবে",
  "vebe": "ভেবে",
  "mone": "মনে",
  "rakho": "রাখো",
  "rakhi": "রাখি",
  "rakhbo": "রাখব",
  "rakha": "রাখা",
  "bhule": "ভুলে",
  "vule": "ভুলে",
  "bhulbo": "ভুলব",
  "vulbo": "ভুলব",
  "ghumai": "ঘুমাই",
  "ghumao": "ঘুমাও",
  "ghumano": "ঘুমানো",
  "uthi": "উঠি",
  "utho": "উঠো",
  "uthbo": "উঠব",
  "bosi": "বসি",
  "boshi": "বসি",
  "boso": "বসো",
  "bosho": "বসো",
  "darao": "দাঁড়াও",
  "dariye": "দাঁড়িয়ে",
  "cholo": "চলো",
  "choli": "চলি",
  "cholbo": "চলব",
  "chola": "চলা",
  "dourai": "দৌড়াই",
  "hashi": "হাসি",
  "hasi": "হাসি",
  "kadi": "কাদি",
  "kado": "কাঁদো",
  "shuni": "শুনি",
  "suni": "শুনি",
  "shono": "শোনো",
  "sono": "শোনো",
  "shunte": "শুনতে",
  "shona": "শোনা",
  "kini": "কিনি",
  "kino": "কিনো",
  "kinbo": "কিনব",
  "bechi": "বেচি",
  "becho": "বেচো",
  "khuji": "খুঁজি",
  "khujo": "খুঁজো",
  "khujchi": "খুঁজছি",
  "pai": "পাই",
  "pao": "পাও",
  "peye": "পেয়ে",
  "peyeci": "পেয়েছি",
  "peyeche": "পেয়েছি",
  "pabo": "পাব",
  "harai": "হারাই",
  "hariye": "হারিয়ে",
  "khuli": "খুলি",
  "kholo": "খোলো",
  "bondho": "বন্ধ",
  "bondo": "বন্ধ",
  "khola": "খোলা",
  "dhoro": "ধরো",
  "dhori": "ধরি",
  "chere": "ছেড়ে",
  "charo": "ছাড়ো",
  "phire": "ফিরে",
  "fire": "ফিরে",
  "phiri": "ফিরি",
  "firi": "ফিরি",
  "phirbo": "ফিরব",
  "firbo": "ফিরব",
  "anbo": "আনব",
  "ano": "আনো",
  "ana": "আনা",
  "pathao": "পাঠাও",
  "pathabo": "পাঠাব",
  "dako": "ডাকো",
  "daki": "ডাকি",
  "kheli": "খেলি",
  "khelo": "খেলো",
  "khelbo": "খেলব",
  "nachi": "নাচি",
  "gai": "গাই",
  "gao": "গাও",
  "kajkori": "কাজ করি",
  "shahajjo": "সাহায্য",
  "sahajjo": "সাহায্য",
  "help": "সাহায্য",
  "shahajjokoro": "সাহায্য করো",
  "nam": "নাম",
  "naam": "নাম",
  "boyos": "বয়স",
  "boyosh": "বয়স",
  "boyesh": "বয়স",
  "bari": "বাড়ি",
  "basha": "বাসা",
  "basa": "বাসা",
  "ghor": "ঘর",
  "desh": "দেশ",
  "deshe": "দেশে",
  "desher": "দেশের",
  "bangladesh": "বাংলাদেশ",
  "banglades": "বাংলাদেশ",
  "bangladesher": "বাংলাদেশের",
  "bangladeshe": "বাংলাদেশে",
  "bangla": "বাংলা",
  "banglar": "বাংলার",
  "dhaka": "ঢাকা",
  "dhakay": "ঢাকায়",
  "dhakai": "ঢাকায়",
  "dhakar": "ঢাকার",
  "rajdhani": "রাজধানী",
  "sohor": "শহর",
  "shohor": "শহর",
  "gram": "গ্রাম",
  "graam": "গ্রাম",
  "manush": "মানুষ",
  "chele": "ছেলে",
  "meye": "মেয়ে",
  "bondhu": "বন্ধু",
  "baba": "বাবা",
  "ma": "মা",
  "maa": "মা",
  "amma": "মা",
  "ammu": "মা",
  "bhai": "ভাই",
  "bon": "বোন",
  "poribar": "পরিবার",
  "mama": "মামা",
  "khala": "খালা",
  "fufu": "ফুফু",
  "phuphu": "ফুফু",
  "chacha": "চাচা",
  "dada": "দাদা",
  "dadi": "দাদি",
  "nana": "নানা",
  "nani": "নানি",
  "chachi": "চাচি",
  "mami": "মামি",
  "shoshur": "শ্বশুর",
  "soshur": "শ্বশুর",
  "shashuri": "শাশুড়ি",
  "shami": "স্বামী",
  "swami": "স্বামী",
  "stri": "স্ত্রী",
  "stree": "স্ত্রী",
  "bou": "স্ত্রী",
  "bow": "বউ",
  "sontan": "সন্তান",
  "shontan": "সন্তান",
  "chelemeye": "ছেলেমেয়ে",
  "nati": "নাতি",
  "natni": "নাতনি",
  "attiyo": "আত্মীয়",
  "attio": "আত্মীয়",
  "protibeshi": "প্রতিবেশী",
  "shikkhok": "শিক্ষক",
  "sikkok": "শিক্ষক",
  "shikkhika": "শিক্ষিকা",
  "chhatro": "ছাত্র",
  "chatro": "ছাত্র",
  "chhatri": "ছাত্রী",
  "daktar": "ডাক্তার",
  "doctor": "ডাক্তার",
  "engineer": "ইঞ্জিনিয়ার",
  "injiniar": "ইঞ্জিনিয়ার",
  "krishok": "কৃষক",
  "mojur": "মজুর",
  "bebsayi": "ব্যবসায়ী",
  "bebshayi": "ব্যবসায়ী",
  "police": "পুলিশ",
  "pulish": "পুলিশ",
  "soinik": "সৈনিক",
  "shoinik": "সৈনিক",
  "kaj": "কাজ",
  "chakri": "চাকরি",
  "poralekha": "পড়ালেখা",
  "porashona": "পড়ালেখা",
  "porashuna": "পড়ালেখা",
  "school": "স্কুল",
  "iskul": "স্কুল",
  "skul": "স্কুল",
  "college": "কলেজ",
  "kolej": "কলেজ",
  "bishwabidyaloy": "বিশ্ববিদ্যালয়",
  "university": "বিশ্ববিদ্যালয়",
  "varsity": "বিশ্ববিদ্যালয়",
  "boi": "বই",
  "khabar": "খাবার",
  "bhat": "ভাত",
  "vat": "ভাত",
  "pani": "পানি",
  "cha": "চা",
  "taka": "টাকা",
  "somoy": "সময়",
  "shomoy": "সময়",
  "rat": "রাত",
  "raat": "রাত",
  "shokal": "সকাল",
  "sokal": "সকাল",
  "bikel": "বিকেল",
  "dupur": "দুপুর",
  "sondha": "সন্ধ্যা",
  "shondha": "সন্ধ্যা",
  "aj": "আজ",
  "aaj": "আজ",
  "ajke": "আজকে",
  "kal": "কাল",
  "kaal": "কাল",
  "kalke": "কালকে",
  "gotokal": "গতকাল",
  "agamikal": "আগামীকাল",
  "porshu": "পরশু",
  "bochor": "বছর",
  "mash": "মাস",
  "mas": "মাস",
  "soptaho": "সপ্তাহ",
  "shoptaho": "সপ্তাহ",
  "ghonta": "ঘণ্টা",
  "gonta": "ঘণ্টা",
  "minute": "মিনিট",
  "minit": "মিনিট",
  "second": "সেকেন্ড",
  "sekend": "সেকেন্ড",
  "abohawa": "আবহাওয়া",
  "abohaoa": "আবহাওয়া",
  "brishti": "বৃষ্টি",
  "bristi": "বৃষ্টি",
  "rod": "রোদ",
  "megh": "মেঘ",
  "meg": "মেঘ",
  "batas": "বাতাস",
  "batash": "বাতাস",
  "gorom": "গরম",
  "thanda": "ঠান্ডা",
  "tanda": "ঠান্ডা",
  "khela": "খেলা",
  "cricket": "ক্রিকেট",
  "kriket": "ক্রিকেট",
  "football": "ফুটবল",
  "futbol": "ফুটবল",
  "khobor": "খবর",
  "khobar": "খবর",
  "songbad": "সংবাদ",
  "shongbad": "সংবাদ",
  "itihas": "ইতিহাস",
  "biggan": "বিজ্ঞান",
  "ganit": "গণিত",
  "gonit": "গণিত",
  "prithibi": "পৃথিবী",
  "akash": "আকাশ",
  "surjo": "সূর্য",
  "shurjo": "সূর্য",
  "chad": "চাঁদ",
  "chand": "চাঁদ",
  "nokkhotro": "নক্ষত্র",
  "nokkhottro": "নক্ষত্র",
  "jonmodin": "জন্মদিন",
  "tarikh": "তারিখ",
  "barta": "বার্তা",
  "proshno": "প্রশ্ন",
  "uttor": "উত্তর",
  "uttar": "উত্তর",
  "totho": "তথ্য",
  "tothyo": "তথ্য",
  "gan": "গান",
  "gaan": "গান",
  "cinema": "সিনেমা",
  "sinema": "সিনেমা",
  "pradhanmontri": "প্রধানমন্ত্রী",
  "prodhanmontri": "প্রধানমন্ত্রী",
  "rashtropoti": "রাষ্ট্রপতি",
  "sorkar": "সরকার",
  "shorkar": "সরকার",
  "montri": "মন্ত্রী",
  "songsod": "সংসদ",
  "shongsod": "সংসদ",
  "nirbachon": "নির্বাচন",
  "vote": "ভোট",
  "bhot": "ভোট",
  "vot": "ভোট",
  "ain": "আইন",
  "adalot": "আদালত",
  "hashpatal": "হাসপাতাল",
  "haspatal": "হাসপাতাল",
  "hospital": "হাসপাতাল",
  "oshudh": "ওষুধ",
  "oshud": "ওষুধ",
  "rog": "রোগ",
  "jor": "জ্বর",
  "kashi": "কাশি",
  "kasi": "কাশি",
  "mathabetha": "মাথাব্যথা",
  "poth": "পথ",
  "rasta": "রাস্তা",
  "gari": "গাড়ি",
  "bus": "বাস",
  "bas": "বাস",
  "train": "ট্রেন",
  "tren": "ট্রেন",
  "plane": "প্লেন",
  "plen": "প্লেন",
  "nodi": "নদী",
  "sagor": "সাগর",
  "shagor": "সাগর",
  "pahar": "পাহাড়",
  "jongol": "জঙ্গল",
  "gach": "গাছ",
  "phul": "ফুল",
  "ful": "ফুল",
  "phol": "ফল",
  "fol": "ফল",
  "mach": "মাছ",
  "machh": "মাছ",
  "mangsho": "মাংস",
  "mangso": "মাংস",
  "dim": "ডিম",
  "dudh": "দুধ",
  "dud": "দুধ",
  "ruti": "রুটি",
  "roti": "রুটি",
  "dal": "ডাল",
  "daal": "ডাল",
  "shobji": "সবজি",
  "sobji": "সবজি",
  "alu": "আলু",
  "aloo": "আলু",
  "peyaz": "পেঁয়াজ",
  "peyaj": "পেঁয়াজ",
  "roshun": "রসুন",
  "rosun": "রসুন",
  "morich": "মরিচ",
  "lobon": "লবণ",
  "tel": "তেল",
  "chini": "চিনি",
  "mishti": "মিষ্টি",
  "misti": "মিষ্টি",
  "pholer": "ফলের",
  "foler": "ফলের",
  "aam": "আম",
  "am": "আম",
  "kola": "কলা",
  "komola": "কমলা",
  "apel": "আপেল",
  "apple": "আপেল",
  "coffee": "কফি",
  "kofi": "কফি",
  "biriyani": "বিরিয়ানি",
  "biryani": "বিরিয়ানি",
  "khichuri": "খিচুড়ি",
  "ilish": "ইলিশ",
  "rui": "রুই",
  "chingri": "চিংড়ি",
  "hilsa": "হিলসা",
  "pitha": "পিঠা",
  "payesh": "পায়েস",
  "payes": "পায়েস",
  "roshogolla": "রসগোল্লা",
  "rosogolla": "রসগোল্লা",
  "shondesh": "সন্দেশ",
  "sondesh": "সন্দেশ",
  "chatni": "চাটনি",
  "achar": "আচার",
  "dosa": "ডোসা",
  "shingara": "সিঙ্গারা",
  "singara": "সিঙ্গারা",
  "somucha": "সমুচা",
  "samosa": "সমুচা",
  "fuchka": "ফুচকা",
  "phuchka": "ফুচকা",
  "jhalmuri": "ঝালমুড়ি",
  "chowmein": "চাউমিন",
  "chaumin": "চাউমিন",
  "noodles": "নুডুলস",
  "nuduls": "নুডুলস",
  "burger": "বার্গার",
  "pizza": "পিজ্জা",
  "ek": "এক",
  "dui": "দুই",
  "tin": "তিন",
  "teen": "তিন",
  "char": "চার",
  "chaar": "চার",
  "pach": "পাঁচ",
  "paach": "পাঁচ",
  "chhoy": "ছয়",
  "choy": "ছয়",
  "soy": "ছয়",
  "sat": "সাত",
  "saat": "সাত",
  "at": "আট",
  "aat": "আট",
  "noy": "নয়",
  "dosh": "দশ",
  "egaro": "এগারো",
  "baro": "বারো",
  "tero": "তেরো",
  "choddo": "চোদ্দো",
  "choddho": "চোদ্দো",
  "ponero": "পনেরো",
  "sholo": "ষোলো",
  "solo": "ষোলো",
  "shotero": "সতেরো",
  "sotero": "সতেরো",
  "atharo": "আঠারো",
  "unish": "উনিশ",
  "bish": "বিশ",
  "trish": "ত্রিশ",
  "chollish": "চল্লিশ",
  "ponchash": "পঞ্চাশ",
  "shat": "ষাট",
  "shottor": "সত্তর",
  "nobboi": "নব্বই",
  "eksho": "একশ",
  "ekso": "একশ",
  "hajar": "হাজার",
  "hazar": "হাজার",
  "lakh": "লাখ",
  "lak": "লাখ",
  "koti": "কোটি",
  "ekta": "একটা",
  "ekti": "একটি",
  "duita": "দুইটা",
  "duta": "দুইটা",
  "duti": "দুটি",
  "tinta": "তিনটা",
  "prothom": "প্রথম",
  "ditiyo": "দ্বিতীয়",
  "ditio": "দ্বিতীয়",
  "tritiyo": "তৃতীয়",
  "sesher": "শেষের",
  "robibar": "রবিবার",
  "sombar": "সোমবার",
  "shombar": "সোমবার",
  "mongolbar": "মঙ্গলবার",
  "budhbar": "বুধবার",
  "budbar": "বুধবার",
  "brihoshpotibar": "বৃহস্পতিবার",
  "bishudbar": "বৃহস্পতিবার",
  "shukrobar": "শুক্রবার",
  "sukrobar": "শুক্রবার",
  "shonibar": "শনিবার",
  "sonibar": "শনিবার",
  "january": "জানুয়ারি",
  "januari": "জানুয়ারি",
  "february": "ফেব্রুয়ারি",
  "februari": "ফেব্রুয়ারি",
  "march": "মার্চ",
  "april": "এপ্রিল",
  "may": "মে",
  "mei": "মে",
  "june": "জুন",
  "jun": "জুন",
  "july": "জুলাই",
  "julai": "জুলাই",
  "august": "আগস্ট",
  "agost": "আগস্ট",
  "september": "সেপ্টেম্বর",
  "october": "অক্টোবর",
  "november": "নভেম্বর",
  "december": "ডিসেম্বর",
  "grishmo": "গ্রীষ্ম",
  "borsha": "বর্ষা",
  "shorot": "শরৎ",
  "sorot": "শরৎ",
  "hemonto": "হেমন্ত",
  "sheet": "শীত",
  "shit": "শীত",
  "boshonto": "বসন্ত",
  "bosonto": "বসন্ত",
  "noboborsho": "নববর্ষ",
  "eid": "ঈদ",
  "id": "ঈদ",
  "puja": "পূজা",
  "ramjan": "রমজান",
  "ramadan": "রমজান",
  "pohela": "পহেলা বৈশাখ",
  "pohelaboishakh": "পহেলা বৈশাখ",
  "chittagong": "চট্টগ্রাম",
  "chottogram": "চট্টগ্রাম",
  "ctg": "চট্টগ্রাম",
  "sylhet": "সিলেট",
  "silet": "সিলেট",
  "rajshahi": "রাজশাহী",
  "khulna": "খুলনা",
  "barisal": "বরিশাল",
  "borishal": "বরিশাল",
  "rangpur": "রংপুর",
  "rongpur": "রংপুর",
  "mymensingh": "ময়মনসিংহ",
  "moymonshing": "ময়মনসিংহ",
  "comilla": "কুমিল্লা",
  "kumilla": "কুমিল্লা",
  "narayanganj": "নারায়ণগঞ্জ",
  "gazipur": "গাজীপুর",
  "jessore": "যশোর",
  "joshor": "যশোর",
  "bogra": "বগুড়া",
  "bogura": "বগুড়া",
  "pabna": "পাবনা",
  "dinajpur": "দিনাজপুর",
  "kushtia": "কুষ্টিয়া",
  "faridpur": "ফরিদপুর",
  "tangail": "টাঙ্গাইল",
  "noakhali": "নোয়াখালী",
  "coxsbazar": "কক্সবাজার",
  "cox": "কক্সবাজার",
  "coxbazar": "কক্সবাজার",
  "sundarban": "সুন্দরবন",
  "sundarbon": "সুন্দরবন",
  "padma": "পদ্মা",
  "jamuna": "যমুনা",
  "meghna": "মেঘনা",
  "bongoposhagor": "বঙ্গোপসাগর",
  "bayofbengal": "বঙ্গোপসাগর",
  "pakistan": "পাকিস্তান",
  "bharot": "ভারত",
  "india": "ভারত",
  "bharat": "ভারত",
  "nepal": "নেপাল",
  "myanmar": "মিয়ানমার",
  "burma": "মিয়ানমার",
  "london": "লন্ডন",
  "america": "আমেরিকা",
  "usa": "আমেরিকা",
  "england": "ইংল্যান্ড",
  "china": "চীন",
  "chin": "চীন",
  "japan": "জাপান",
  "saudi": "সৌদি",
  "saudiarabia": "সৌদি",
  "makkah": "মক্কা",
  "mecca": "মক্কা",
  "madina": "মদিনা",
  "medina": "মদিনা",
  "bhalo": "ভালো",
  "valo": "ভালো",
  "bhalu": "ভালো",
  "kharap": "খারাপ",
  "bharap": "খারাপ",
  "boro": "বড়",
  "choto": "ছোট",
  "notun": "নতুন",
  "puran": "পুরান",
  "purano": "পুরনো",
  "purono": "পুরনো",
  "sundor": "সুন্দর",
  "sundar": "সুন্দর",
  "shundor": "সুন্দর",
  "darun": "দারুণ",
  "osadharon": "অসাধারণ",
  "onek": "অনেক",
  "beshi": "বেশি",
  "kom": "কম",
  "shob": "সব",
  "sob": "সব",
  "sobai": "সবাই",
  "shobai": "সবাই",
  "aro": "আরও",
  "aroo": "আরও",
  "arek": "আরেক",
  "aar": "আর",
  "ar": "আর",
  "taratari": "তাড়াতাড়ি",
  "aste": "আস্তে",
  "dhire": "ধীরে",
  "sotti": "সত্যি",
  "shoti": "সত্যি",
  "mittha": "মিথ্যা",
  "thik": "ঠিক",
  "tik": "ঠিক",
  "bhul": "ভুল",
  "vul": "ভুল",
  "sohoj": "সহজ",
  "kothin": "কঠিন",
  "dorkar": "দরকার",
  "proyojon": "প্রয়োজন",
  "sombhob": "সম্ভব",
  "shombhob": "সম্ভব",
  "osombhob": "অসম্ভব",
  "khub": "খুব",
  "ekdom": "একদম",
  "ekdum": "একদম",
  "puro": "পুরো",
  "khali": "খালি",
  "bhora": "ভরা",
  "vora": "ভরা",
  "gorib": "গরীব",
  "dhoni": "ধনী",
  "doni": "ধনী",
  "buddhiman": "বুদ্ধিমান",
  "buddiman": "বুদ্ধিমান",
  "boka": "বোকা",
  "shokto": "শক্ত",
  "sokto": "শক্ত",
  "norom": "নরম",
  "mota": "মোটা",
  "chikon": "চিকন",
  "lomba": "লম্বা",
  "khato": "খাটো",
  "uchu": "উঁচু",
  "unchu": "উঁচু",
  "nichu": "নিচু",
  "kachakachi": "কাছাকাছি",
  "dure": "দূরে",
  "kache": "কাছে",
  "bhitore": "ভিতরে",
  "vitore": "ভিতরে",
  "baire": "বাইরে",
  "shamne": "সামনে",
  "samne": "সামনে",
  "pichone": "পিছনে",
  "dane": "ডানে",
  "bame": "বামে",
  "upore": "উপরে",
  "niche": "নিচে",
  "moddhe": "মধ্যে",
  "pashe": "পাশে",
  "na": "না",
  "naa": "না",
  "ha": "হ্যাঁ",
  "hya": "হ্যাঁ",
  "hae": "হ্যাঁ",
  "haan": "হ্যাঁ",
  "yes": "হ্যাঁ",
  "jodi": "যদি",
  "tahole": "তাহলে",
  "kintu": "কিন্তু",
  "tobe": "তবে",
  "karon": "কারণ",
  "jonno": "জন্য",
  "jonne": "জন্য",
  "theke": "থেকে",
  "porjonto": "পর্যন্ত",
  "sathe": "সাথে",
  "shathe": "সাথে",
  "soho": "সহ",
  "chara": "ছাড়া",
  "onno": "অন্য",
  "matro": "মাত্র",
  "abar": "আবার",
  "tao": "তাও",
  "oboshoi": "অবশ্যই",
  "obosshoi": "অবশ্যই",
  "ebong": "এবং",
  "ba": "বা",
  "othoba": "অথবা",
  "je": "যে",
  "ja": "যা",
  "jeta": "যেটা",
  "jara": "যারা",
  "jokhon": "যখন",
  "jekhane": "যেখানে",
  "jemon": "যেমন",
  "temon": "তেমন",
  "emon": "এমন",
  "o": "ও",
  "to": "তো",
  "naki": "না কি",
  "kina": "কি না",
  "hoyto": "হয়তো",
  "hoyni": "হয়নি",
  "hoini": "হয়নি",
  "nahole": "নাহলে",
  "tai": "তাই",
  "sejonno": "সেজন্য",
  "phole": "ফলে",
  "fole": "ফলে",
  "poreo": "পরেও",
  "agei": "আগেই",
  "ekhono": "এখনো",
  "ekhono2": "এখনও",
  "itimoddhe": "ইতিমধ্যে",
  "shighroi": "শীঘ্রই",
  "sighroi": "শীঘ্রই",
  "hothat": "হঠাৎ",
  "dhiredhire": "ধীরে ধীরে",
  "eksate": "একসাথে",
  "eksathe": "একসাথে",
  "alada": "আলাদা",
  "ekoi": "একই",
  "bhinno": "ভিন্ন",
  "vinno": "ভিন্ন",
  "shoman": "সমান",
  "soman": "সমান",
  "besh": "বেশ",
  "pray": "প্রায়",
  "prai": "প্রায়",
  "prayi": "প্রায়ই",
  "kodachit": "কদাচিৎ",
  "shobshomoy": "সবসময়",
  "sobsomoy": "সবসময়",
  "kokhono": "কখনো",
  "kokhonoi": "কখনোই",
  "kothao": "কোথাও",
  "kothaona": "কোথাও না",
  "jekeu": "যে কেউ",
  "jekono": "যেকোনো",
  "kichuna": "কিছু না",
  "shobkichu": "সবকিছু",
  "sobkichu": "সবকিছু",
  "kichuta": "কিছুটা",
  "purota": "পুরোটা",
  "ordhek": "অর্ধেক",
  "salam": "সালাম",
  "assalamualaikum": "আসসালামু আলাইকুম",
  "slamalikum": "আসসালামু আলাইকুম",
  "assalamu": "আসসালামু আলাইকুম",
  "salamalaikum": "আসসালামু আলাইকুম",
  "nomoskar": "নমস্কার",
  "namaskar": "নমস্কার",
  "adab": "আদাব",
  "dhonnobad": "ধন্যবাদ",
  "dhonnbad": "ধন্যবাদ",
  "donnobad": "ধন্যবাদ",
  "shukriya": "শুকরিয়া",
  "sukriya": "শুকরিয়া",
  "sorry": "দুঃখিত",
  "dukkhito": "দুঃখিত",
  "bidae": "বিদায়",
  "bidaay": "বিদায়",
  "tata": "টাটা",
  "bhalobasi": "ভালোবাসি",
  "valobasi": "ভালোবাসি",
  "pochondo": "পছন্দ",
  "posondo": "পছন্দ",
  "shubhosokal": "শুভ সকাল",
  "goodmorning": "শুভ সকাল",
  "shubhoratri": "শুভ রাত্রি",
  "goodnight": "শুভ রাত্রি",
  "kemonaacho": "কেমন আছো",
  "shagotom": "স্বাগতম",
  "swagotom": "স্বাগতম",
  "maafkoro": "মাফ করো",
  "maaf": "মাফ করো",
  "khoma": "ক্ষমা",
  "doyakore": "দয়া করে",
  "doya": "দয়া করে",
  "onugroho": "অনুগ্রহ",
  "obhinondon": "অভিনন্দন",
  "shubheccha": "শুভেচ্ছা",
  "subheccha": "শুভেচ্ছা",
  "mobarak": "মোবারক",
  "mubarak": "মোবারক",
  "eidmubarak": "ঈদ মোবারক",
  "shubhojonmodin": "জন্মদিন শুভ",
  "matha": "মাথা",
  "chokh": "চোখ",
  "cokh": "চোখ",
  "kan": "কান",
  "nak": "নাক",
  "mukh": "মুখ",
  "dat": "দাঁত",
  "daat": "দাঁত",
  "jibh": "জিভ",
  "jib": "জিভ",
  "hat": "হাত",
  "haat": "হাত",
  "pa": "পা",
  "paa": "পা",
  "pet": "পেট",
  "pith": "পিঠ",
  "pit": "পিঠ",
  "hridoy": "হৃদয়",
  "rokto": "রক্ত",
  "har": "হাড়",
  "haar": "হাড়",
  "chul": "চুল",
  "twok": "ত্বক",
  "tok": "ত্বক",
  "phone": "ফোন",
  "fon": "ফোন",
  "mobile": "মোবাইল",
  "mobail": "মোবাইল",
  "computer": "কম্পিউটার",
  "kompiutar": "কম্পিউটার",
  "internet": "ইন্টারনেট",
  "intarnet": "ইন্টারনেট",
  "email": "ইমেইল",
  "imel": "ইমেইল",
  "message": "মেসেজ",
  "mesej": "মেসেজ",
  "chobi": "ছবি",
  "video": "ভিডিও",
  "bhideo": "ভিডিও",
  "ganbajna": "গানবাজনা",
  "tv": "টিভি",
  "tivi": "টিভি",
  "radio": "রেডিও",
  "khoborerkagoj": "খবরের কাগজ",
  "newspaper": "খবরের কাগজ",
  "kolom": "কলম",
  "kagoj": "কাগজ",
  "table": "টেবিল",
  "tebil": "টেবিল",
  "chair": "চেয়ার",
  "chear": "চেয়ার",
  "bichana": "বিছানা",
  "balish": "বালিশ",
  "kapord": "কাপড়",
  "kapor": "কাপড়",
  "juta": "জুতা",
  "shirt": "শার্ট",
  "shart": "শার্ট",
  "pant": "প্যান্ট",
  "sari": "শাড়ি",
  "sharee": "শাড়ি",
  "lungi": "লুঙ্গি",
  "tupi": "টুপি",
  "chata": "ছাতা",
  "bag": "ব্যাগ",
  "byag": "ব্যাগ",
  "chabi": "চাবি",
  "tala": "তালা",
  "dorja": "দরজা",
  "janala": "জানালা",
  "deyal": "দেয়াল",
  "chad2": "ছাদ",
  "chhad": "ছাদ",
  "rannaghor": "রান্নাঘর",
  "bathroom": "বাথরুম",
  "bathrum": "বাথরুম",
  "toilet": "টয়লেট",
  "ranna": "রান্না",
  "dhowa": "ধোয়া",
  "dhoa": "ধোয়া",
  "porishkar": "পরিষ্কার",
  "poriskar": "পরিষ্কার",
  "moyla": "ময়লা",
  "moila": "ময়লা",
  "aborjona": "আবর্জনা",
  "panikhoroch": "পানিখরচ",
  "biddyut": "বিদ্যুৎ",
  "biddut": "বিদ্যুৎ",
  "current": "বিদ্যুৎ",
  "gas": "গ্যাস",
  "gyas": "গ্যাস",
  "agun": "আগুন",
  "panifutano": "পানি ফুটানো",
  "fridge": "ফ্রিজ",
  "frij": "ফ্রিজ",
  "chula": "চুলা",
  "hari": "হাড়ি",
  "thala": "থালা",
  "bati": "বাটি",
  "glass": "গ্লাস",
  "glas": "গ্লাস",
  "chumuk": "চুমুক",
  "dokan": "দোকান",
  "bajar": "বাজার",
  "bazar": "বাজার",
  "dam": "দাম",
  "daam": "দাম",
  "shosta": "সস্তা",
  "sosta": "সস্তা",
  "dami": "দামি",
  "bikri": "বিক্রি",
  "kena": "কেনা",
  "hisab": "হিসাব",
  "bank": "ব্যাংক",
  "byank": "ব্যাংক",
  "account": "একাউন্ট",
  "ekaunt": "একাউন্ট",
  "rin": "ঋণ",
  "reen": "ঋণ",
  "sud": "সুদ",
  "shud": "সুদ",
  "beton": "বেতন",
  "ay": "আয়",
  "aay": "আয়",
  "byay": "ব্যয়",
  "byoy": "ব্যয়",
  "sonchoy": "সঞ্চয়",
  "shonchoy": "সঞ্চয়",
  "rickshaw": "রিকশা",
  "riksha": "রিকশা",
  "cng": "সিএনজি",
  "launch": "লঞ্চ",
  "lonch": "লঞ্চ",
  "steamer": "স্টিমার",
  "ferry": "ফেরি",
  "pool": "পুল",
  "pul": "পুল",
  "setu": "সেতু",
  "shethu": "সেতু",
  "padmasetu": "পদ্মা সেতু",
  "jatiosongsod": "জাতীয় সংসদ",
  "shahjalal": "শাহজালাল",
  "hazrat": "হযরত",
  "mosjid": "মসজিদ",
  "masjid": "মসজিদ",
  "mondir": "মন্দির",
  "girja": "গির্জা",
  "eidgah": "ঈদগাহ",
  "quran": "কোরআন",
  "kuran": "কোরআন",
  "namaj": "নামাজ",
  "namaz": "নামাজ",
  "roja": "রোজা",
  "roza": "রোজা",
  "hajj": "হজ",
  "hoj": "হজ",
  "doa": "দোয়া",
  "duaa": "দোয়া",
  "allah": "আল্লাহ",
  "alla": "আল্লাহ",
  "nobi": "নবী",
  "nabi": "নবী",
  "rasul": "রাসুল",
  "rasool": "রাসুল",
  "islam": "ইসলাম",
  "muslim": "মুসলিম",
  "hindu": "হিন্দু",
  "christian": "খ্রিস্টান",
  "khristan": "খ্রিস্টান",
  "boudho": "বৌদ্ধ",
  "buddho": "বৌদ্ধ",
  "dhormo": "ধর্ম",
  "dhorom": "ধর্ম",
  "bhasha": "ভাষা",
  "basha2": "ভাষা",
  "vasha": "ভাষা",
  "shongskriti": "সংস্কৃতি",
  "songskriti": "সংস্কৃতি",
  "oitijjo": "ঐতিহ্য",
  "shadhinota": "স্বাধীনতা",
  "sadhinota": "স্বাধীনতা",
  "muktijuddho": "মুক্তিযুদ্ধ",
  "muktijoddha": "মুক্তিযোদ্ধা",
  "bijoy": "বিজয়",
  "potaka": "পতাকা",
  "jatio": "জাতীয়",
  "ganer": "গানের",
  "kobi": "কবি",
  "lekhok": "লেখক",
  "kobita": "কবিতা",
  "golpo": "গল্প",
  "uponnash": "উপন্যাস",
  "uponash": "উপন্যাস",
  "natok": "নাটক",
  "ovineta": "অভিনেতা",
  "ovinetri": "অভিনেত্রী",
  "cricketer": "ক্রিকেটার",
  "kriketer": "ক্রিকেটার",
  "kheloar": "খেলোয়াড়",
  "kheloyar": "খেলোয়াড়",
  "dol": "দল",
  "match": "ম্যাচ",
  "mech": "ম্যাচ",
  "goal": "গোল",
  "gol": "গোল",
  "run": "রান",
  "ran": "রান",
  "wicket": "উইকেট",
  "wiket": "উইকেট",
  "bat": "ব্যাট",
  "byat": "ব্যাট",
  "ball": "বল",
  "bol2": "বল",
  "stadium": "স্টেডিয়াম",
  "dorshok": "দর্শক",
  "joy": "জয়",
  "porajoy": "পরাজয়",
  "draw": "ড্র",
  "dro": "ড্র",
  "worldcup": "ওয়ার্ল্ডকাপ",
  "t20": "টি২০",
  "odi": "ওডিআই",
  "test": "টেস্ট",
  "testmatch": "টেস্ট",
  "koree": "করি",
  "koroo": "করো",
  "korb": "করব",
  "korbe": "করবে",
  "korchhi": "করছি",
  "korchhe": "করছে",
  "korlen": "করলেন",
  "korchis": "করছিস",
  "korli": "করলি",
  "kors": "করস",
  "bolee": "বলি",
  "boloo": "বলো",
  "bolb": "বলব",
  "bolbe": "বলবে",
  "bolchhi": "বলছি",
  "bolche": "বলছে",
  "bolchhe": "বলছে",
  "bollen": "বললেন",
  "bolba": "বলবা",
  "bolchis": "বলছিস",
  "bolli": "বললি",
  "bols": "বলস",
  "janee": "জানি",
  "janoo": "জানো",
  "jane": "জানে",
  "janb": "জানব",
  "janbe": "জানবে",
  "janchhi": "জানছি",
  "janche": "জানছে",
  "janchhe": "জানছে",
  "janlen": "জানলেন",
  "janle": "জানলে",
  "janun": "জানুন",
  "janba": "জানবা",
  "janchis": "জানছিস",
  "janli": "জানলি",
  "jans": "জানস",
  "dekhee": "দেখি",
  "dekhoo": "দেখো",
  "dekhb": "দেখব",
  "dekhbe": "দেখবে",
  "dekhchhi": "দেখছি",
  "dekhche": "দেখছে",
  "dekhchhe": "দেখছে",
  "dekhlen": "দেখলেন",
  "dekhle": "দেখলে",
  "dekhba": "দেখবা",
  "dekhchis": "দেখছিস",
  "dekhli": "দেখলি",
  "dekhs": "দেখস",
  "khaee": "খাি",
  "khaoo": "খাো",
  "khae": "খাে",
  "khab": "খাব",
  "khabe": "খাবে",
  "khachi": "খাছি",
  "khachhi": "খাছি",
  "khache": "খাছে",
  "khachhe": "খাছে",
  "khalam": "খালাম",
  "khalen": "খালেন",
  "khale": "খালে",
  "khate": "খাতে",
  "khaa": "খাা",
  "khaun": "খাুন",
  "khaen": "খােন",
  "khaba": "খাবা",
  "khachis": "খাছিস",
  "khas": "খাস",
  "jaee": "যাি",
  "jaoo": "যাো",
  "jae": "যাে",
  "jab": "যাব",
  "jabe": "যাবে",
  "jachi": "যাছি",
  "jachhi": "যাছি",
  "jache": "যাছে",
  "jachhe": "যাছে",
  "jalam": "যালাম",
  "jalen": "যালেন",
  "jale": "যালে",
  "jate": "যাতে",
  "jaa": "যাা",
  "jaun": "যাুন",
  "jaen": "যােন",
  "jaba": "যাবা",
  "jachis": "যাছিস",
  "jali": "যালি",
  "jas": "যাস",
  "ashee": "আসি",
  "ashoo": "আসো",
  "ashe": "আসে",
  "ashbo": "আসব",
  "ashb": "আসব",
  "ashchi": "আসছি",
  "ashchhi": "আসছি",
  "ashche": "আসছে",
  "ashchhe": "আসছে",
  "ashlam": "আসলাম",
  "ashlen": "আসলেন",
  "ashle": "আসলে",
  "ashte": "আসতে",
  "ashen": "আসেন",
  "ashba": "আসবা",
  "ashchis": "আসছিস",
  "ashli": "আসলি",
  "ashs": "আসস",
  "paree": "পারি",
  "paroo": "পারো",
  "pare": "পারে",
  "parb": "পারব",
  "parchi": "পারছি",
  "parchhi": "পারছি",
  "parche": "পারছে",
  "parchhe": "পারছে",
  "parlen": "পারলেন",
  "parle": "পারলে",
  "parte": "পারতে",
  "parun": "পারুন",
  "parba": "পারবা",
  "parchis": "পারছিস",
  "parli": "পারলি",
  "pars": "পারস",
  "thakee": "থাকি",
  "thakoo": "থাকো",
  "thake": "থাকে",
  "thakbo": "থাকব",
  "thakb": "থাকব",
  "thakchhi": "থাকছি",
  "thakche": "থাকছে",
  "thakchhe": "থাকছে",
  "thaklen": "থাকলেন",
  "thakte": "থাকতে",
  "thakun": "থাকুন",
  "thakba": "থাকবা",
  "thakchis": "থাকছিস",
  "thakli": "থাকলি",
  "thaks": "থাকস",
  "rakhee": "রাখি",
  "rakhoo": "রাখো",
  "rakhe": "রাখে",
  "rakhb": "রাখব",
  "rakhbe": "রাখবে",
  "rakhchi": "রাখছি",
  "rakhchhi": "রাখছি",
  "rakhche": "রাখছে",
  "rakhchhe": "রাখছে",
  "rakhlam": "রাখলাম",
  "rakhlen": "রাখলেন",
  "rakhle": "রাখলে",
  "rakhte": "রাখতে",
  "rakhun": "রাখুন",
  "rakhen": "রাখেন",
  "rakhba": "রাখবা",
  "rakhchis": "রাখছিস",
  "rakhli": "রাখলি",
  "rakhs": "রাখস",
  "likhi": "লিখি",
  "likhee": "লিখি",
  "likhoo": "লিখো",
  "likhb": "লিখব",
  "likhbe": "লিখবে",
  "likhchhi": "লিখছি",
  "likhche": "লিখছে",
  "likhchhe": "লিখছে",
  "likhlam": "লিখলাম",
  "likhlen": "লিখলেন",
  "likhle": "লিখলে",
  "likhte": "লিখতে",
  "likha": "লিখা",
  "likhun": "লিখুন",
  "likhen": "লিখেন",
  "likhba": "লিখবা",
  "likhchis": "লিখছিস",
  "likhli": "লিখলি",
  "likhs": "লিখস",
  "poree": "পড়ি",
  "poroo": "পড়ো",
  "porb": "পড়ব",
  "porbe": "পড়বে",
  "porchhi": "পড়ছি",
  "porche": "পড়ছে",
  "porchhe": "পড়ছে",
  "porlam": "পড়লাম",
  "porlen": "পড়লেন",
  "porle": "পড়লে",
  "porun": "পড়ুন",
  "poren": "পড়েন",
  "porba": "পড়বা",
  "porchis": "পড়ছিস",
  "porli": "পড়লি",
  "pors": "পড়স",
  "bujhee": "বুঝি",
  "bujhoo": "বুঝো",
  "bujhe": "বুঝে",
  "bujhbo": "বুঝব",
  "bujhb": "বুঝব",
  "bujhbe": "বুঝবে",
  "bujhchi": "বুঝছি",
  "bujhchhi": "বুঝছি",
  "bujhche": "বুঝছে",
  "bujhchhe": "বুঝছে",
  "bujhlen": "বুঝলেন",
  "bujhle": "বুঝলে",
  "bujha": "বুঝা",
  "bujhun": "বুঝুন",
  "bujhba": "বুঝবা",
  "bujhchis": "বুঝছিস",
  "bujhli": "বুঝলি",
  "bujhs": "বুঝস",
  "bhabee": "ভাবি",
  "bhaboo": "ভাবো",
  "bhabe": "ভাবে",
  "bhabbo": "ভাবব",
  "bhabb": "ভাবব",
  "bhabbe": "ভাববে",
  "bhabchhi": "ভাবছি",
  "bhabche": "ভাবছে",
  "bhabchhe": "ভাবছে",
  "bhablam": "ভাবলাম",
  "bhablen": "ভাবলেন",
  "bhable": "ভাবলে",
  "bhabte": "ভাবতে",
  "bhaba": "ভাবা",
  "bhabun": "ভাবুন",
  "bhaben": "ভাবেন",
  "bhabba": "ভাববা",
  "bhabchis": "ভাবছিস",
  "bhabli": "ভাবলি",
  "bhabs": "ভাবস",
  "shunee": "শুনি",
  "shuno": "শুনো",
  "shunoo": "শুনো",
  "shune": "শুনে",
  "shunbo": "শুনব",
  "shunb": "শুনব",
  "shunbe": "শুনবে",
  "shunchi": "শুনছি",
  "shunchhi": "শুনছি",
  "shunche": "শুনছে",
  "shunchhe": "শুনছে",
  "shunlam": "শুনলাম",
  "shunlen": "শুনলেন",
  "shunle": "শুনলে",
  "shuna": "শুনা",
  "shunun": "শুনুন",
  "shunen": "শুনেন",
  "shunba": "শুনবা",
  "shunchis": "শুনছিস",
  "shunli": "শুনলি",
  "shuns": "শুনস",
  "khelee": "খেলি",
  "kheloo": "খেলো",
  "khele": "খেলে",
  "khelb": "খেলব",
  "khelbe": "খেলবে",
  "khelchi": "খেলছি",
  "khelchhi": "খেলছি",
  "khelche": "খেলছে",
  "khelchhe": "খেলছে",
  "khellam": "খেললাম",
  "khellen": "খেললেন",
  "khelle": "খেললে",
  "khelte": "খেলতে",
  "khelun": "খেলুন",
  "khelen": "খেলেন",
  "khelba": "খেলবা",
  "khelchis": "খেলছিস",
  "khelli": "খেললি",
  "khels": "খেলস",
  "dhoree": "ধরি",
  "dhoroo": "ধরো",
  "dhore": "ধরে",
  "dhorbo": "ধরব",
  "dhorb": "ধরব",
  "dhorbe": "ধরবে",
  "dhorchi": "ধরছি",
  "dhorchhi": "ধরছি",
  "dhorche": "ধরছে",
  "dhorchhe": "ধরছে",
  "dhorlam": "ধরলাম",
  "dhorlen": "ধরলেন",
  "dhorle": "ধরলে",
  "dhorte": "ধরতে",
  "dhora": "ধরা",
  "dhorun": "ধরুন",
  "dhoren": "ধরেন",
  "dhorba": "ধরবা",
  "dhorchis": "ধরছিস",
  "dhorli": "ধরলি",
  "dhors": "ধরস",
  "kholi": "খুলি",
  "kholee": "খুলি",
  "kholoo": "খুলো",
  "khole": "খুলে",
  "kholbo": "খুলব",
  "kholb": "খুলব",
  "kholbe": "খুলবে",
  "kholchi": "খুলছি",
  "kholchhi": "খুলছি",
  "kholche": "খুলছে",
  "kholchhe": "খুলছে",
  "khollam": "খুললাম",
  "khollen": "খুললেন",
  "kholle": "খুললে",
  "kholte": "খুলতে",
  "kholun": "খুলুন",
  "kholen": "খুলেন",
  "kholba": "খুলবা",
  "kholchis": "খুলছিস",
  "kholli": "খুললি",
  "khols": "খুলস",
  "cholee": "চলি",
  "choloo": "চলো",
  "chole": "চলে",
  "cholb": "চলব",
  "cholbe": "চলবে",
  "cholchi": "চলছি",
  "cholchhi": "চলছি",
  "cholche": "চলছে",
  "cholchhe": "চলছে",
  "chollam": "চললাম",
  "chollen": "চললেন",
  "cholle": "চললে",
  "cholte": "চলতে",
  "cholun": "চলুন",
  "cholen": "চলেন",
  "cholba": "চলবা",
  "cholchis": "চলছিস",
  "cholli": "চললি",
  "chols": "চলস",
  "uthee": "উঠি",
  "uthoo": "উঠো",
  "uthe": "উঠে",
  "uthb": "উঠব",
  "uthbe": "উঠবে",
  "uthchi": "উঠছি",
  "uthchhi": "উঠছি",
  "uthche": "উঠছে",
  "uthchhe": "উঠছে",
  "uthlam": "উঠলাম",
  "uthlen": "উঠলেন",
  "uthle": "উঠলে",
  "uthte": "উঠতে",
  "utha": "উঠা",
  "uthun": "উঠুন",
  "uthen": "উঠেন",
  "uthba": "উঠবা",
  "uthchis": "উঠছিস",
  "uthli": "উঠলি",
  "uths": "উঠস",
  "bosee": "বসি",
  "bosoo": "বসো",
  "bose": "বসে",
  "bosbo": "বসব",
  "bosb": "বসব",
  "bosbe": "বসবে",
  "boschi": "বসছি",
  "boschhi": "বসছি",
  "bosche": "বসছে",
  "boschhe": "বসছে",
  "boslam": "বসলাম",
  "boslen": "বসলেন",
  "bosle": "বসলে",
  "boste": "বসতে",
  "bosa": "বসা",
  "bosun": "বসুন",
  "bosen": "বসেন",
  "bosba": "বসবা",
  "boschis": "বসছিস",
  "bosli": "বসলি",
  "boss": "বসস",
  "hashee": "হাসি",
  "hasho": "হাসো",
  "hashoo": "হাসো",
  "hashe": "হাসে",
  "hashbo": "হাসব",
  "hashb": "হাসব",
  "hashbe": "হাসবে",
  "hashchi": "হাসছি",
  "hashchhi": "হাসছি",
  "hashche": "হাসছে",
  "hashchhe": "হাসছে",
  "hashlam": "হাসলাম",
  "hashlen": "হাসলেন",
  "hashle": "হাসলে",
  "hashte": "হাসতে",
  "hasha": "হাসা",
  "hashun": "হাসুন",
  "hashen": "হাসেন",
  "hashba": "হাসবা",
  "hashchis": "হাসছিস",
  "hashli": "হাসলি",
  "hashs": "হাসস",
  "kadee": "কাঁদি",
  "kadoo": "কাঁদো",
  "kade": "কাঁদে",
  "kadbo": "কাঁদব",
  "kadb": "কাঁদব",
  "kadbe": "কাঁদবে",
  "kadchi": "কাঁদছি",
  "kadchhi": "কাঁদছি",
  "kadche": "কাঁদছে",
  "kadchhe": "কাঁদছে",
  "kadlam": "কাঁদলাম",
  "kadlen": "কাঁদলেন",
  "kadle": "কাঁদলে",
  "kadte": "কাঁদতে",
  "kada": "কাঁদা",
  "kadun": "কাঁদুন",
  "kaden": "কাঁদেন",
  "kadba": "কাঁদবা",
  "kadchis": "কাঁদছিস",
  "kadli": "কাঁদলি",
  "kads": "কাঁদস",
  "kinee": "কিনি",
  "kinoo": "কিনো",
  "kine": "কিনে",
  "kinb": "কিনব",
  "kinbe": "কিনবে",
  "kinchi": "কিনছি",
  "kinchhi": "কিনছি",
  "kinche": "কিনছে",
  "kinchhe": "কিনছে",
  "kinlam": "কিনলাম",
  "kinlen": "কিনলেন",
  "kinle": "কিনলে",
  "kinte": "কিনতে",
  "kinun": "কিনুন",
  "kinen": "কিনেন",
  "kinba": "কিনবা",
  "kinchis": "কিনছিস",
  "kinli": "কিনলি",
  "kins": "কিনস",
  "beji": "বেচি",
  "bejee": "বেচি",
  "bejo": "বেচো",
  "bejoo": "বেচো",
  "beje": "বেচে",
  "bejbo": "বেচব",
  "bejb": "বেচব",
  "bejbe": "বেচবে",
  "bejchi": "বেচছি",
  "bejchhi": "বেচছি",
  "bejche": "বেচছে",
  "bejchhe": "বেচছে",
  "bejlam": "বেচলাম",
  "bejlen": "বেচলেন",
  "bejle": "বেচলে",
  "bejte": "বেচতে",
  "beja": "বেচা",
  "bejun": "বেচুন",
  "bejen": "বেচেন",
  "bejba": "বেচবা",
  "bejchis": "বেচছিস",
  "bejli": "বেচলি",
  "bejs": "বেচস",
  "khujee": "খুঁজি",
  "khujoo": "খুঁজো",
  "khuje": "খুঁজে",
  "khujbo": "খুঁজব",
  "khujb": "খুঁজব",
  "khujbe": "খুঁজবে",
  "khujchhi": "খুঁজছি",
  "khujche": "খুঁজছে",
  "khujchhe": "খুঁজছে",
  "khujlam": "খুঁজলাম",
  "khujlen": "খুঁজলেন",
  "khujle": "খুঁজলে",
  "khujte": "খুঁজতে",
  "khuja": "খুঁজা",
  "khujun": "খুঁজুন",
  "khujen": "খুঁজেন",
  "khujba": "খুঁজবা",
  "khujchis": "খুঁজছিস",
  "khujli": "খুঁজলি",
  "khujs": "খুঁজস",
  "paee": "পাি",
  "paoo": "পাো",
  "pae": "পাে",
  "pab": "পাব",
  "pabe": "পাবে",
  "pachi": "পাছি",
  "pachhi": "পাছি",
  "pache": "পাছে",
  "pachhe": "পাছে",
  "palam": "পালাম",
  "palen": "পালেন",
  "pale": "পালে",
  "pate": "পাতে",
  "paun": "পাুন",
  "paen": "পােন",
  "paba": "পাবা",
  "pachis": "পাছিস",
  "pali": "পালি",
  "pas": "পাস",
  "dii": "দিি",
  "diee": "দিি",
  "dio": "দিো",
  "dioo": "দিো",
  "die": "দিে",
  "dib": "দিব",
  "dibe": "দিবে",
  "dichi": "দিছি",
  "dichhi": "দিছি",
  "diche": "দিছে",
  "dichhe": "দিছে",
  "dilen": "দিলেন",
  "dile": "দিলে",
  "dia": "দিা",
  "diun": "দিুন",
  "dien": "দিেন",
  "diba": "দিবা",
  "dichis": "দিছিস",
  "dili": "দিলি",
  "dis": "দিস",
  "nii": "নিি",
  "niee": "নিি",
  "nio": "নিো",
  "nioo": "নিো",
  "nie": "নিে",
  "nib": "নিব",
  "nibe": "নিবে",
  "nichi": "নিছি",
  "nichhi": "নিছি",
  "nichhe": "নিছে",
  "nilen": "নিলেন",
  "nile": "নিলে",
  "nia": "নিা",
  "niun": "নিুন",
  "nien": "নিেন",
  "niba": "নিবা",
  "nichis": "নিছিস",
  "nili": "নিলি",
  "nis": "নিস",
  "ani": "আনি",
  "anee": "আনি",
  "anoo": "আনো",
  "ane": "আনে",
  "anb": "আনব",
  "anbe": "আনবে",
  "anchi": "আনছি",
  "anchhi": "আনছি",
  "anche": "আনছে",
  "anchhe": "আনছে",
  "anlam": "আনলাম",
  "anlen": "আনলেন",
  "anle": "আনলে",
  "ante": "আনতে",
  "anun": "আনুন",
  "anen": "আনেন",
  "anba": "আনবা",
  "anchis": "আনছিস",
  "anli": "আনলি",
  "ans": "আনস",
  "pathai": "পাঠাি",
  "pathaee": "পাঠাি",
  "pathaoo": "পাঠাো",
  "pathae": "পাঠাে",
  "pathab": "পাঠাব",
  "pathabe": "পাঠাবে",
  "pathachi": "পাঠাছি",
  "pathachhi": "পাঠাছি",
  "pathache": "পাঠাছে",
  "pathachhe": "পাঠাছে",
  "pathalam": "পাঠালাম",
  "pathalen": "পাঠালেন",
  "pathale": "পাঠালে",
  "pathate": "পাঠাতে",
  "pathaa": "পাঠাা",
  "pathaun": "পাঠাুন",
  "pathaen": "পাঠােন",
  "pathaba": "পাঠাবা",
  "pathachis": "পাঠাছিস",
  "pathali": "পাঠালি",
  "pathas": "পাঠাস",
  "dakee": "ডাকি",
  "dakoo": "ডাকো",
  "dake": "ডাকে",
  "dakbo": "ডাকব",
  "dakb": "ডাকব",
  "dakbe": "ডাকবে",
  "dakchi": "ডাকছি",
  "dakchhi": "ডাকছি",
  "dakche": "ডাকছে",
  "dakchhe": "ডাকছে",
  "daklam": "ডাকলাম",
  "daklen": "ডাকলেন",
  "dakle": "ডাকলে",
  "dakte": "ডাকতে",
  "daka": "ডাকা",
  "dakun": "ডাকুন",
  "daken": "ডাকেন",
  "dakba": "ডাকবা",
  "dakchis": "ডাকছিস",
  "dakli": "ডাকলি",
  "daks": "ডাকস",
  "nachee": "নাচি",
  "nacho": "নাচো",
  "nachoo": "নাচো",
  "nache": "নাচে",
  "nachbo": "নাচব",
  "nachb": "নাচব",
  "nachbe": "নাচবে",
  "nachchi": "নাচছি",
  "nachchhi": "নাচছি",
  "nachche": "নাচছে",
  "nachchhe": "নাচছে",
  "nachlam": "নাচলাম",
  "nachlen": "নাচলেন",
  "nachle": "নাচলে",
  "nachte": "নাচতে",
  "nacha": "নাচা",
  "nachun": "নাচুন",
  "nachen": "নাচেন",
  "nachba": "নাচবা",
  "nachchis": "নাচছিস",
  "nachli": "নাচলি",
  "nachs": "নাচস",
  "gaee": "গাি",
  "gaoo": "গাো",
  "gae": "গাে",
  "gabo": "গাব",
  "gab": "গাব",
  "gabe": "গাবে",
  "gachi": "গাছি",
  "gachhi": "গাছি",
  "gache": "গাছে",
  "gachhe": "গাছে",
  "galam": "গালাম",
  "galen": "গালেন",
  "gale": "গালে",
  "gate": "গাতে",
  "gaa": "গাা",
  "gaun": "গাুন",
  "gaen": "গােন",
  "gaba": "গাবা",
  "gachis": "গাছিস",
  "gali": "গালি",
  "ghumi": "ঘুমি",
  "ghumee": "ঘুমি",
  "ghumo": "ঘুমো",
  "ghumoo": "ঘুমো",
  "ghume": "ঘুমে",
  "ghumbo": "ঘুমব",
  "ghumb": "ঘুমব",
  "ghumbe": "ঘুমবে",
  "ghumchi": "ঘুমছি",
  "ghumchhi": "ঘুমছি",
  "ghumche": "ঘুমছে",
  "ghumchhe": "ঘুমছে",
  "ghumlam": "ঘুমলাম",
  "ghumlen": "ঘুমলেন",
  "ghumle": "ঘুমলে",
  "ghumte": "ঘুমতে",
  "ghuma": "ঘুমা",
  "ghumun": "ঘুমুন",
  "ghumen": "ঘুমেন",
  "ghumba": "ঘুমবা",
  "ghumchis": "ঘুমছিস",
  "ghumli": "ঘুমলি",
  "ghums": "ঘুমস",
  "phori": "ফিরি",
  "phoree": "ফিরি",
  "phoro": "ফিরো",
  "phoroo": "ফিরো",
  "phore": "ফিরে",
  "phorbo": "ফিরব",
  "phorb": "ফিরব",
  "phorbe": "ফিরবে",
  "phorchi": "ফিরছি",
  "phorchhi": "ফিরছি",
  "phorche": "ফিরছে",
  "phorchhe": "ফিরছে",
  "phorlam": "ফিরলাম",
  "phorlen": "ফিরলেন",
  "phorle": "ফিরলে",
  "phorte": "ফিরতে",
  "phora": "ফিরা",
  "phorun": "ফিরুন",
  "phoren": "ফিরেন",
  "phorba": "ফিরবা",
  "phorchis": "ফিরছিস",
  "phorli": "ফিরলি",
  "phors": "ফিরস",
  "chari": "ছাড়ি",
  "charee": "ছাড়ি",
  "charoo": "ছাড়ো",
  "chare": "ছাড়ে",
  "charbo": "ছাড়ব",
  "charb": "ছাড়ব",
  "charbe": "ছাড়বে",
  "charchi": "ছাড়ছি",
  "charchhi": "ছাড়ছি",
  "charche": "ছাড়ছে",
  "charchhe": "ছাড়ছে",
  "charlam": "ছাড়লাম",
  "charlen": "ছাড়লেন",
  "charle": "ছাড়লে",
  "charte": "ছাড়তে",
  "charun": "ছাড়ুন",
  "charen": "ছাড়েন",
  "charba": "ছাড়বা",
  "charchis": "ছাড়ছিস",
  "charli": "ছাড়লি",
  "chars": "ছাড়স",
};

/** Rough phonetic fallback for Banglish words that are not in the dictionary. */
const PHONETIC_RULES: [RegExp, string][] = [
  // longest clusters first
  [/ksh/g, "ক্ষ"], [/ng/g, "ং"],
  [/kh/g, "খ"], [/gh/g, "ঘ"], [/chh/g, "ছ"], [/ch/g, "চ"], [/jh/g, "ঝ"],
  [/th/g, "থ"], [/dh/g, "ধ"], [/ph/g, "ফ"], [/bh/g, "ভ"], [/sh/g, "শ"], [/rh/g, "ঢ"],
  [/aa/g, "আ"], [/ee/g, "ঈ"], [/ii/g, "ঈ"], [/oo/g, "উ"], [/uu/g, "ঊ"],
  [/oi/g, "ঐ"], [/ou/g, "ঔ"], [/ai/g, "ঐ"],
  [/v/g, "ভ"], [/f/g, "ফ"], [/w/g, "ও"], [/z/g, "জ"],
];

/**
 * A Latin word "looks Banglish" when it is not an ordinary English word but
 * has Bangla-typical letter clusters / endings.
 */
const BANGLISH_HINTS = /(?:^|[^a-z])(?:ki|ke|keno|kobe|kothay|kivabe|kemon|ami|amar|tumi|tomar|apni|ache|hobe|korbo|kore|bolo|jani|nam|bhalo|valo|onek|khub|dhonnobad|kemon)(?:[^a-z]|$)/;

/** English words that also appear in the Banglish dictionary — never a signal. */
const AMBIGUOUS = new Set([
  "ma", "na", "ha", "ke", "ki", "se", "she", "ache", "tara", "kal", "din", "boi", "cha",
  "news", "school", "cricket", "football", "sorry", "gram", "help", "yes", "phone",
  "mobile", "computer", "internet", "email", "message", "video", "tv", "radio",
  "newspaper", "table", "chair", "bathroom", "toilet", "current", "gas", "glass",
  "bank", "account", "rickshaw", "cng", "launch", "steamer", "ferry", "pool",
  "pakistan", "india", "nepal", "myanmar", "burma", "london", "america", "usa",
  "england", "china", "japan", "saudi", "mecca", "medina", "islam", "muslim",
  "hindu", "christian", "quran", "hajj", "allah", "match", "goal", "run", "wicket",
  "bat", "ball", "stadium", "draw", "worldcup", "odi", "test", "january", "february",
  "march", "april", "may", "june", "july", "august", "september", "october",
  "november", "december", "eid", "ramadan", "puja", "apple", "coffee", "pizza",
  "burger", "noodles", "dosa", "samosa", "bus", "train", "plane", "vote", "doctor",
  "college", "university", "varsity", "hospital", "minute", "second", "engineer",
  "police", "age", "to", "o", "ba", "ar", "am", "at", "id", "cox", "jan", "para",
  "bola", "take", "hat", "pet", "pa", "kan", "nak", "bag", "shirt", "pant",
  "dam", "rin", "tel", "dal", "dim", "fol", "ful", "gach", "poth", "rog", "jor",
  "ain", "joy", "dol", "ran", "bol", "the", "and", "for", "are", "was", "is", "it",
  "in", "on", "of", "my", "me", "you", "we", "they", "this", "that", "here",
  "there", "now", "then", "after", "before", "go", "come", "see", "know", "tell",
  "say", "do", "did", "can", "will", "please", "good", "bad", "new", "old", "big",
  "small", "day", "night", "time", "year", "month", "week", "hour", "name",
  "home", "house", "city", "country", "people", "friend", "family", "food",
  "water", "tea", "rice", "money", "work", "job", "book", "play", "game",
  "weather", "rain", "sun", "moon", "star", "earth", "history", "science",
  "math", "question", "answer", "info", "song", "film", "movie", "government",
  "minister", "president", "capital", "bangladesh", "bangla", "dhaka", "pore",
  "kora", "dekha", "thaka", "kha", "ja", "di", "ni", "an", "ga", "s", "e", "a",
  "i", "b", "be", "bo", "le", "li", "en", "un", "te", "chi", "che", "lam", "len",
  "fire", "today", "lunch", "after", "with", "this", "about", "alan", "turing",
  "weather", "london", "bad", "today", "will", "school", "language", "english",
]);

/**
 * Detect whether a message is Bangla script, Banglish (Bangla in Latin) or
 * plain English. Mixed messages resolve to whichever side dominates.
 */
export function detectLanguage(text: string): Lang {
  const t = (text || "").trim();
  if (!t) return "en";

  const ratio = bengaliRatio(t);
  if (ratio >= 0.35) return "bn";

  if (!LATIN_RE.test(t)) return ratio > 0 ? "bn" : "en";

  const words = t.toLowerCase().match(/[a-z]+/g) ?? [];
  if (words.length === 0) return "en";

  let banglishHits = 0;
  for (const w of words) {
    if (AMBIGUOUS.has(w)) continue;
    if (BANGLISH_WORDS[w]) banglishHits++;
  }

  const score = banglishHits / words.length;
  // Two solid Banglish words, or a third of the message, or a clear cluster.
  if (banglishHits >= 2 || score >= 0.34 || (banglishHits >= 1 && BANGLISH_HINTS.test(" " + t.toLowerCase() + " "))) {
    return "banglish";
  }
  return ratio > 0.1 ? "bn" : "en";
}

/** Transliterate ONE Banglish word (dictionary first, phonetics as fallback). */
export function banglishWord(word: string, phonetic = false): string | null {
  const w = word.toLowerCase();
  const direct = BANGLISH_WORDS[w];
  if (direct) return direct;
  if (!phonetic || w.length < 3) return null;
  let out = w;
  for (const [re, rep] of PHONETIC_RULES) out = out.replace(re, rep);
  return out === w ? null : out;
}

/**
 * Rewrite a Banglish sentence into Bengali script. Words that are not in the
 * dictionary are kept as-is — this is deliberately conservative, because a
 * wrong transliteration hurts search more than an untranslated word.
 */
export function banglishToBengali(text: string): string {
  return (text || "").replace(/[A-Za-z]+/g, (w) => banglishWord(w) ?? w);
}

/**
 * Bengali → Latin overrides. Several Bengali spellings mean the same thing
 * ("কি"/"কী", "ভালো"/"ভাল"), and matching must fold them onto ONE token.
 */
const REVERSE_OVERRIDES: Record<string, string> = {
  "কী": "ki", "কি": "ki", "কে": "ke", "কেন": "keno", "কীভাবে": "kivabe",
  "কিভাবে": "kivabe", "কোথায়": "kothay", "কখন": "kokhon", "কবে": "kobe",
  "কত": "koto", "কার": "kar", "কাকে": "kake", "কেমন": "kemon",
  "আমার": "amar", "আমি": "ami", "আমাকে": "amake", "আমরা": "amra",
  "তোমার": "tomar", "তুমি": "tumi", "আপনি": "apni", "আপনার": "apnar",
  "নাম": "nam", "ভালো": "bhalo", "ভাল": "bhalo", "খারাপ": "kharap",
  "ধন্যবাদ": "dhonnobad", "আছে": "ache", "আছো": "acho", "আছেন": "achen",
  "হবে": "hobe", "সময়": "somoy", "খবর": "khobor", "আবহাওয়া": "abohawa",
  "মনে": "mone", "রাখো": "rakho", "পছন্দ": "pochondo", "সম্পর্কে": "somporke",
  "জান": "jani", "জানো": "jani", "জানেন": "jani", "বল": "bolo", "বলো": "bolo",
  "সাহায্য": "help", "তারিখ": "tarikh", "আজ": "aj", "আজকে": "aj",
  // greetings & farewells
  "হাই": "hi", "হ্যালো": "hello", "হেলো": "hello",
  "আসসালামু": "assalamualaikum", "আলাইকুম": "alaikum", "সালাম": "salam",
  "নমস্কার": "nomoskar", "আদাব": "adab",
  "বিদায়": "bidae", "আল্লাহ": "allah", "হাফেজ": "hafez", "খোদা": "khoda",
  // misc high-traffic words
  "কয়টা": "koyta", "বাজে": "baje", "বাংলা": "bangla", "বাংলাদেশ": "bangladesh",
  "বুঝো": "bujho", "বুঝেন": "bujho", "বুঝি": "bujhi", "ভুলে": "bhule",
  "প্রশ্ন": "proshno", "উত্তর": "uttor", "সব": "shob", "সবকিছু": "shob",
  "ইতিহাস": "itihas", "রাজধানী": "rajdhani", "প্রধানমন্ত্রী": "pradhanmontri",
};

/** Reverse map (Bengali → Banglish) built once from the dictionary. */
const BENGALI_TO_LATIN: Record<string, string> = (() => {
  const map: Record<string, string> = {};
  for (const [latin, bengali] of Object.entries(BANGLISH_WORDS)) {
    // First spelling wins — the dictionary lists the canonical one first.
    if (!map[bengali]) map[bengali] = latin;
  }
  return { ...map, ...REVERSE_OVERRIDES };
})();

/** Rewrite a Bengali sentence into its Banglish (Latin) form where possible. */
export function bengaliToBanglish(text: string): string {
  return (text || "").replace(/[\u0980-\u09FF]+/g, (w) => BENGALI_TO_LATIN[w] ?? w);
}

/**
 * ONE canonical lowercase Latin form for any of the three languages.
 *
 *   "আমার নাম কী"          → "amar nam ki"
 *   "Amar naam ki?"        → "amar nam ki"
 *   "what is my name?"     → "what is my name"
 *
 * Intents and memory rules match against this, so a single pattern covers
 * English, Bangla and Banglish at once.
 */
export function normalizeForMatch(text: string): string {
  let t = (text || "").toLowerCase().trim();
  // Bengali → Latin so one pattern can match every script.
  t = t.replace(/[\u0980-\u09FF]+/g, (w) => BENGALI_TO_LATIN[w] ?? w);
  // Canonicalise the many Banglish spellings to their first dictionary form.
  t = t.replace(/[a-z]+/g, (w) => {
    const bengali = BANGLISH_WORDS[w];
    if (!bengali) return w;
    return BENGALI_TO_LATIN[bengali] ?? w;
  });
  // Drop punctuation, collapse whitespace. \p{M} keeps Bengali vowel signs and
  // the hasanta attached to their letters (সর্বশেষ must stay ONE word).
  return t.replace(/[^\p{L}\p{N}\p{M}\s]+/gu, " ").replace(/\s+/g, " ").trim();
}

/** Every useful spelling of a message — used to widen search + matching. */
export function languageVariants(text: string): string[] {
  const raw = (text || "").trim();
  const out = new Set<string>();
  if (raw) out.add(raw);
  const lang = detectLanguage(raw);
  if (lang === "banglish") {
    const bn = banglishToBengali(raw);
    if (bn && bn !== raw) out.add(bn);
  }
  if (lang === "bn") {
    const latin = bengaliToBanglish(raw);
    if (latin && latin !== raw) out.add(latin);
  }
  const norm = normalizeForMatch(raw);
  if (norm && norm !== raw.toLowerCase()) out.add(norm);
  return [...out];
}

// ---------------------------------------------------------------------------
// Reply localisation
// ---------------------------------------------------------------------------

export interface Localized {
  en: string;
  bn: string;
  /** Optional Banglish variant — falls back to `bn` when omitted. */
  banglish?: string;
}

/** Pick the reply text that matches the language the user wrote in. */
export function t(lang: Lang, text: Localized): string {
  if (lang === "bn") return text.bn;
  if (lang === "banglish") return text.banglish ?? text.bn;
  return text.en;
}

/** Convenience: detect + localise in one call. */
export function reply(input: string, text: Localized): string {
  return t(detectLanguage(input), text);
}
